### ISSUE TITLE
Weird Sneak Place event bug

### ISSUE THREAD

**Issue by LunafeyLazuli** [Thuts-Mods/ThutCore#7]
When Sneak-placing blocks, they don't actually place and when you [unch the block again they disappear and goes back into your inventory. Assuming it's a conflict with Quark, but yeah

Version: thutcore-1.18.1-8.4.0.jar

[26.12 16:23:39] [Server] [Server thread/ERROR]: Exception caught during firing event: Tried to query PermissionNode 'thutcore.thutcore.subbiome.set' although it has not been Registered
[26.12 16:23:39] [Server] 	Index10
[26.12 16:23:39] [Server] 	Listeners:
[26.12 16:23:39] [Server] 		HIGHEST
[26.12 16:23:39] [Server] 		ASM: com.github.elrol.elrolsutilities.events.BlockEventHandler@4bec51a8 interactEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		HIGH
[26.12 16:23:39] [Server] 		ASM: class net.mehvahdjukaar.supplementaries.common.events.ServerEvents onRightClickBlockHigh(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		NORMAL
[26.12 16:23:39] [Server] 		ASM: com.lothrazar.customgamerules.event.RuleEvents@7779085 onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: class com.mrh0.buildersaddition.event.GameEvents interact(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: me.thonk.croptopia.events.Harvest@471baf3 onHarvest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$4022/0x00000008016260d0@59cc6e4b
[26.12 16:23:39] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$4022/0x00000008016260d0@58c71fd1
[26.12 16:23:39] [Server] 		ASM: class thut.core.proxy.CommonProxy interactRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: class thut.core.init.CommonInit interactRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: class com.minecolonies.coremod.event.EventHandler onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: class org.samo_lego.taterzens.forge.event.EventHandler onBlockInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: class com.simibubi.create.foundation.tileEntity.behaviour.linked.LinkHandler onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: class com.simibubi.create.foundation.tileEntity.behaviour.filtering.FilteringHandler onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: class com.simibubi.create.foundation.tileEntity.behaviour.edgeInteraction.EdgeInteractionHandler onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: class com.simibubi.create.foundation.block.ItemUseOverrides onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: class com.simibubi.create.content.logistics.block.funnel.FunnelItem funnelItemAlwaysPlacesWhenUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: class com.simibubi.create.content.contraptions.components.flywheel.engine.FurnaceEngineBlock usingFurnaceEngineOnFurnacePreventsGUI(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: class vazkii.quark.base.handler.ToolInteractionHandler itemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: vazkii.quark.content.building.module.StoolsModule@6ccb1f30 itemUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: vazkii.quark.content.building.module.ShearVinesModule@9259960 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: vazkii.quark.content.tweaks.module.SimpleHarvestModule@36d2298 onClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: vazkii.quark.content.tweaks.module.SignEditingModule@2d175ba3 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: vazkii.quark.content.tweaks.module.ReplaceScaffoldingModule@4b9e293 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: vazkii.quark.content.tweaks.module.EnhancedLaddersModule@5ccb7f25 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: vazkii.quark.addons.oddities.module.MatrixEnchantingModule@59d1f389 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: de.maxhenkel.reap.CropEvents@4c114c41 onPlayerUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$4022/0x00000008016260d0@288e98a7
[26.12 16:23:39] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$4022/0x00000008016260d0@657a2de3
[26.12 16:23:39] [Server] 		ASM: class thut.core.common.ThutCore$MobEvents interact(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: de.ellpeck.naturesaura.events.CommonEvents@7816e28f onItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: com.natamus.nohostilesaroundcampfire.events.CampfireEvent@2d57eb6c onRightClickCampfireBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: com.minecolonies.coremod.permissions.ColonyPermissionEventHandler@9ae7863 on(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[26.12 16:23:39] [Server] 		ASM: com.minecolonies.coremod.permissions.ColonyPermissionEventHandler@1ff4f405 on(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[26.12 16:23:39] [Server] 		ASM: com.minecolonies.coremod.permissions.ColonyPermissionEventHandler@2ec1cf11 on(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[26.12 16:23:39] [Server] 		ASM: com.minecolonies.coremod.permissions.ColonyPermissionEventHandler@1b52f7d3 on(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[26.12 16:23:39] [Server] 		ASM: com.lothrazar.customgamerules.event.RuleEvents@7779085 onNonLivingEntityTick(Lnet/minecraftforge/event/entity/EntityEvent;)V
[26.12 16:23:39] [Server] 		LOW
[26.12 16:23:39] [Server] 		ASM: class net.mehvahdjukaar.supplementaries.common.events.ServerEvents onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		LOWEST
[26.12 16:23:39] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$4022/0x00000008016260d0@5f7eb931
[26.12 16:23:39] [Server] 		ASM: class ovh.corail.tombstone.event.EventHandler onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[26.12 16:23:39] [Server] 		ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem consumeDurabilityOnPlace(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[26.12 16:23:39] [Server] net.minecraftforge.server.permission.exceptions.UnregisteredPermissionExceptionTried to query PermissionNode 'thutcore.thutcore.subbiome.set' although it has not been Registered
[26.12 16:23:39] [Server] 	at TRANSFORMER/forge@39.0.8/net.minecraftforge.server.permission.PermissionAPI.getPermission(PermissionAPI.java:82)
[26.12 16:23:39] [Server] 	at TRANSFORMER/thutcore@8.4.0/thut.api.util.PermNodes.getBooleanPerm(PermNodes.java:76)
[26.12 16:23:39] [Server] 	at TRANSFORMER/thutcore@8.4.0/thut.core.proxy.CommonProxy.getSubbiome(CommonProxy.java:63)
[26.12 16:23:39] [Server] 	at TRANSFORMER/thutcore@8.4.0/thut.core.proxy.CommonProxy.isSubbiomeEditor(CommonProxy.java:75)
[26.12 16:23:39] [Server] 	at TRANSFORMER/thutcore@8.4.0/thut.core.proxy.CommonProxy.interactRightClickBlock(CommonProxy.java:82)
[26.12 16:23:39] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler_435_CommonProxy_interactRightClickBlock_RightClickBlock.invoke(.dynamic)
[26.12 16:23:39] [Server] 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[26.12 16:23:39] [Server] 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[26.12 16:23:39] [Server] 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[26.12 16:23:39] [Server] 	at TRANSFORMER/forge@39.0.8/net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:739)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:315)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:975)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.TickTask.run(TickTask.java:18)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672)
[26.12 16:23:39] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
[26.12 16:23:39] [Server] 	at java.base/java.lang.Thread.run(Thread.java:833)
[26.12 16:23:39] [Server] [Server thread/FATAL]: Error executing task on Server
[26.12 16:23:39] [Server] net.minecraftforge.server.permission.exceptions.UnregisteredPermissionExceptionTried to query PermissionNode 'thutcore.thutcore.subbiome.set' although it has not been Registered
[26.12 16:23:39] [Server] 	at net.minecraftforge.server.permission.PermissionAPI.getPermission(PermissionAPI.java:82) ~[forge-1.18.1-39.0.8-universal.jar%23182!:?]
[26.12 16:23:39] [Server] 	at thut.api.util.PermNodes.getBooleanPerm(PermNodes.java:76) ~[thutcore-1.18.1-8.4.0.jar%23165!:8.4.0]
[26.12 16:23:39] [Server] 	at thut.core.proxy.CommonProxy.getSubbiome(CommonProxy.java:63) ~[thutcore-1.18.1-8.4.0.jar%23165!:8.4.0]
[26.12 16:23:39] [Server] 	at thut.core.proxy.CommonProxy.isSubbiomeEditor(CommonProxy.java:75) ~[thutcore-1.18.1-8.4.0.jar%23165!:8.4.0]
[26.12 16:23:39] [Server] 	at thut.core.proxy.CommonProxy.interactRightClickBlock(CommonProxy.java:82) ~[thutcore-1.18.1-8.4.0.jar%23165!:8.4.0]
[26.12 16:23:39] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler_435_CommonProxy_interactRightClickBlock_RightClickBlock.invoke(.dynamic) ~[?:?]
[26.12 16:23:39] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?]
[26.12 16:23:39] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
[26.12 16:23:39] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
[26.12 16:23:39] [Server] 	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:739) ~[forge-1.18.1-39.0.8-universal.jar%23182!:?]
[26.12 16:23:39] [Server] 	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:315) ~[server-1.18.1-20211210.034407-srg.jar%23178!:?]
[26.12 16:23:39] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:975) ~[server-1.18.1-20211210.034407-srg.jar%23178!:?]
[26.12 16:23:39] [Server] 	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[server-1.18.1-20211210.034407-srg.jar%23178!:?]
[26.12 16:23:39] [Server] 	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%23178!:?]
[26.12 16:23:39] [Server] 	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23178!:?]
[26.12 16:23:39] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23178!:?]
[26.12 16:23:39] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23178!:?]
[26.12 16:23:39] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23178!:?]
[26.12 16:23:39] [Server] 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%23178!:?]
[26.12 16:23:39] [Server] 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23178!:?]

**Comment by Thutmose** [comment]
See if the version in the zip here makes any difference?


[thutcore-1.18.1-8.4.1.jar.zip](https://github.com/Thuts-Mods/ThutCore/files/7780131/thutcore-1.18.1-8.4.1.jar.zip)

The jar file is inside the zip as github comments don't allow .jar files...

**Comment by StrangeThistle** [comment]
I can confirm that 8.4.0 broke shift-right-click even as the only mod loaded (it also disabled that tool function for several other mods in a pack in addition to sneak placing blocks) and that 8.4.1 fixes the issue. After spending the last several hours isolating the problem (I was working through around 90 mods), I am happy I can just grab the fix here and not have to wait for an update on the Curse launcher.

**Comment by LunafeyLazuli** [comment]
Thank you loads for looking into it!

**Comment by LunafeyLazuli** [comment]
Will the new jar be updated on curseforge?

**Comment by Thutmose** [comment]
the version 8.5.0 on curseforge should include this fix
